version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the configuration          
      - cd docker_conf-in-s3
      - ./build_conf_codebuild.sh
  post_build:
    commands:
      - echo Build completed on `date` 
